### ISSUE TITLE
Steps to run a single attack on windows system

### ISSUE THREAD

**Issue by mehwish-aman** [FuChong-cyber/label-inference-attacks#3]
Hey!
I am new to VFL. I want to run this code but I didnt understand the instructions given in read.md file.
Kindly guide me with all the steps to run this code for only single attack(active attack) on windows system.
Thanks in advance..

**Comment by FuChong-cyber** [comment]
Are you familiar with Anaconda? 
1. You can install Anaconda and create a virtual environment ''my_venv'' (or whatever name you like). 
2. Open a command prompt window on windows system, navigate to the directory where you store these codes
3. Type ''conda activate my_venv'' to activate the virtual environment
4. Use .bat files to run attacks, as demonstrated in Readme

If there are errors indicating that some packages are missing, use pip to install them.

**Comment by mehwish-aman** [comment]
@FuChong-cyber  Thankyou for the reply! 
I already followed all these steps, actually I was stuck in running .bat files.
 Now its all working..
Thankyou soo much.
