### ISSUE TITLE
复现cifar10数据集训练基础框架的第二行命令时，损失值始终为nan

### ISSUE THREAD

**Issue by bloom0705** [FuChong-cyber/label-inference-attacks#4]
您好，打算复现原论文中的模型补全算法，想问一下run_training.bat与run_model_completion.bat中的三行指令分别代表什么呢？还有跑python vfl_framework.py --use-mal-optim True --use-mal-optim-all False --use-mal-optim-top False -d CIFAR10 --path-dataset ./data/CIFAR10  --k 4 --epochs 100 --half 16 该命令时，loss值始终为NAN，请问这是正常现象吗

**Comment by FuChong-cyber** [comment]
--use-mal-optim指的是攻击者是否使用local malicious optimizer
 --use-mal-optim-all指的是，是否所有参与方全部开启malicious optimizer（无论出于攻击还是防御目的）
  --use-mal-optim-top指的是，是否对于top model也使用malicious optimizer（当时设计这个是为了测试可能的防御，发现防御效果一般）
  
  loss值是NAN肯定不正常，可以检查下学习率是否过大，或者malicious optimizer的scaling rate是否过大

**Comment by bloom0705** [comment]
好的谢谢您，现在已经了解了
&nbsp;


AD钙奶
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月7日(星期三) 下午3:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FuChong-cyber/label-inference-attacks] 复现cifar10数据集训练基础框架的第二行命令时，损失值始终为nan (Issue #4)





 
--use-mal-optim指的是攻击者是否使用local malicious optimizer
 --use-mal-optim-all指的是，是否所有参与方全部开启malicious optimizer（无论出于攻击还是防御目的）
 --use-mal-optim-top指的是，是否对于top model也使用malicious optimizer（当时设计这个是为了测试可能的防御，发现防御效果一般）
 
loss值是NAN肯定不正常，可以检查下学习率是否过大，或者malicious optimizer的scaling rate是否过大

**Comment by zhaocaibei123** [comment]
![image](https://github.com/FuChong-cyber/label-inference-attacks/assets/48509226/90e63c8d-14a1-41c3-b349-073a5c40423b)
80行会导致p.grad和param_state['momentum_buffer']是同一个tensor，在91行乘ratio的时候momentum也乘了ratio，ratio>1会一直放大momentum，然后参数会变很大 loss nan
