### ISSUE TITLE
MaliciousSGD每个step是否需要append last_parameters_grads

### ISSUE THREAD

**Issue by zhaocaibei123** [FuChong-cyber/label-inference-attacks#5]
![image](https://github.com/FuChong-cyber/label-inference-attacks/assets/48509226/0f5bab42-21e0-492d-896b-001689633cdd)
看上去只有第一个step需要append，后面的step append也没用，还是用的第一次append进去的list

**Comment by FuChong-cyber** [comment]
确实是个问题，会导致资源浪费。已经修复，谢谢！

**Comment by zhaocaibei123** [comment]
> 确实是个问题，会导致资源浪费。已经修复，谢谢！

还请看看上个issue，momentum似乎有点问题 :)
